---
title: "Estimation and Hypothesis Testing"
author: "Brayan Duran Medina"
output: html_document
---

# Importing libraries
```{r}
library(readxl)
library(stats)
```

# Read data from Excel file
```{r}
data <- read_excel("GSS_1972_2014.xlsx")
```

# Print column names
```{r}
colnames(data)
```

# Correct answers to eleven Science questions
```{r}
correct_answers <- c("True", "False", "True", "False", "True",
                     "False", "True", "True", "True",
                     "Earth around sun", "One year")
```

# Extract people from year 2014
```{r}
data_2014 <- data[data$"Gss year for this respondent" == 2014, ]

data_2014
```

# Extract columns names with answers to Science questions
```{r}
science_questions <- colnames(data_2014)[c(42:52)]

science_questions
```

# Add new column with number of correct answers
```{r}
data_2014$correct_answers <- NA


for (i in seq_len(nrow(data_2014))) {
  data_2014$correct_answers[i] <-
    sum(data_2014[i, science_questions] == correct_answers)
}

data_2014$correct_answers
```

# ANOVA test for demographic variables
```{r}

anova_result <- aov(correct_answers ~
                      data_2014$`Respondents sex` +
                        data_2014$`Age of respondent` +
                        data_2014$`Race of respondent` +
                        data_2014$`Marital status` +
                        data_2014$`Number of children` +
                        data_2014$`Highest year of school completed` +
                        data_2014$`Sexual orientation` +
                        data_2014$`Respondents income` +
                        data_2014$`Does r own or rent home?`, data = data_2014)

summary(anova_result)
```

# TukeyHSD test for demographic variables
```{r}
tukey_result <- TukeyHSD(anova_result)

tukey_result
```